# Generated by Django 4.2.7 on 2023-11-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_client_trial_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trial_period_days',
            field=models.IntegerField(default=30),
        ),
    ]
